name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@afc83dbbf4e7e32e04649e29dbf30668d30e9e3e
      with:
        version: '2020.04.05'
    - uses: actions/checkout@v4.1.0
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@12.1
      with:
        cli: 1.11.1.1413
    - name: Lint
      run: ./lint.sh

  tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Prepare JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@12.1
      with:
        cli: 1.11.1.1413
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
        key: v1-${{ hashFiles('./deps.edn') }}-postgres
        restore-keys: |
          v1-${{ hashFiles('./deps.edn') }}-
          v1-
    - run: clojure -X:dev:test
      name: Run tests
      env:
        CI: TRUE

  codespell:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_file: .codespellignore
